//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CordovaIconSplashGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\MobileResponder.CH\\MobileResponder.Apps\\MRKapoZH\\MRKapoZH\\res")]
        public string rootPath {
            get {
                return ((string)(this["rootPath"]));
            }
            set {
                this["rootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\MobileResponder.CH\\MobileResponder.Apps\\MRKapoZH\\MRKapoZH\\res\\splash.png")]
        public string splashPath {
            get {
                return ((string)(this["splashPath"]));
            }
            set {
                this["splashPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\MobileResponder.CH\\MobileResponder.Apps\\MRKapoZH\\MRKapoZH\\res\\icon.png")]
        public string iconPath {
            get {
                return ((string)(this["iconPath"]));
            }
            set {
                this["iconPath"] = value;
            }
        }
    }
}
